document.write("¡Quiero formar parte de EmpleaONE!");
document.write("<br>");
document.write("Los resultados de la tabla del 8 son:");
document.write("<br>");
document.write("8x1=",8*1);
document.write("<br>");
document.write("8x2=",8*2);
document.write("<br>");
document.write("8x3=",8*3);
document.write("<br>");
document.write("8x4=",8*4);
document.write("<br>");
document.write("8x5=",8*5);
document.write("<br>");
document.write("8x6=",8*6);
document.write("<br>");
document.write("8x7=",8*7);
document.write("<br>");
document.write("8x8=",8*8);
document.write("<br>");
document.write("8x9=",8*9);
document.write("<br>");
document.write("8x10=",8*10);